sudo: false
language: node_js  
jobs:
  include:
    - stage: test
      script:
        - echo 'Build starts!!'
        - echo 'Installing Deps!'
        - npm test
    - stage: deploy
      script:
        - echo 'anal sex master'
    - stage: deploy2
      script:
        - echo 'anal sex master teen'
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master
  - name: deploy2
    # require the type to be push to master
    if: type = pull AND branch = master
    
    
    
# node_js:
# #  - "4"
#   - "5"
# script:
#   - echo 'Build starts!!'
#   - echo 'Installing Deps!'
#   - npm test
# after_success:
#   - echo 'Billy'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
# deploy:
# provider: script
# script: ballsack.sh
# on:
#   all_branches: true
#   condition: $TRAVIS_BRANCH =~ ^(master)$
